### ISSUE TITLE
[API] Remove the usage of `System.Drawing.Rectangle` from the public API

### ISSUE THREAD

**Issue by jhm-ciberman** [rds1983/FontStashSharp#17]
The namespace `System.Drawing` is only fully supported on windows, and for all graphics programming related is now recomended to use `System.Numerics`.  So I think it would be an improvement to remove completely the use of `System.Drawing.Rectangle` from the interface `IFontStashRenderer` and replace the nullable `Rectangle? src` by two non nullable arguments `Vector2 uv, Vector2 deltaUV`.  (or uvTopLeft and uvTopRight, it's the same)

```csharp
namespace FontStashSharp.Interfaces
{
    public interface IFontStashRenderer
    {
        void Draw(
            object texture, 
            Vector2 position, 
            Vector2 size, 
            Vector2 uv, 
            Vector2 deltaUV, 
            Color color, 
            float rotation, 
            Vector2 origin, 
            Vector2 scale, 
            float depth);
    }
}
```

It would benefit a lot those like us who use FontStashSharp in a custom renderer and it will have no impact for people who use another well known renderer (since you can easily convert those two `System.Numerics.Vector2` to a `System.Drawing.Rectangle`.)

**Comment by rds1983** [comment]
Unsure about this. As I am pretty sure that micro subet of System.Drawing that is used by FontStashSharp is supported by all platforms. So why change well-established API that was already implemented by some people?
Moreover FontStashSharp uses System.Drawing.Color, how will we replace it?

**Comment by jhm-ciberman** [comment]
Yes. You are right. I thing I thought it would be a good idea but since Color is on the same package I think it should be referenced anyway.
