### ISSUE TITLE
FreeType renderer does not work under linux

### ISSUE THREAD

**Issue by Beyley** [rds1983/FontStashSharp#31]
It always tries to load a non-existant library, which then fails then crashes out

**Comment by rds1983** [comment]
Well, after some thoughts, I've moved whole FreeType renderer code to the CustomRasterizers sample. Moreover it'll work only under Windows.
Not the best way to address an issue, but a working one. :)

**Comment by Beyley** [comment]
> Well, after some thoughts, I've moved whole FreeType renderer code to the CustomRasterizers sample. Moreover it'll work only under Windows. Not the best way to address an issue, but a working one. :)

in that case ill try to get it working on both windows and linux then PR it in :^)
(only didnt do that before cus lazy)

**Comment by Beyley** [comment]
after some extensive testing, i have determined that by removing the 6 after the library name, the library loader is smart enough to pick up on the linux system version, and for windows, you can just change the filename, so i guess ill PR my change
