### ISSUE TITLE
[Feature Request] Get draw position and size substring inside of string

### ISSUE THREAD

**Issue by Beyley** [rds1983/FontStashSharp#32]
Say for example i have a string that i draw containing `abcde` and i want to get the draw position and size of `bcd` inside the string, with 0,0 being the position where `a` is approximately drawn, this is mainly so i can figure out the position and size of selected text in my engine's text box implementation, as currently i just guess

**Comment by rds1983** [comment]
try method GetGlyphRects

**Comment by Beyley** [comment]
> try method GetGlyphRects

Oh i didnt see that function, it seems to be what im looking for
