### ISSUE TITLE
which of the multiple TTFs do you get with GetFont? 

### ISSUE THREAD

**Issue by zissakos** [rds1983/FontStashSharp#6]
In your example you add 3 TTFs with fontSystem.AddFont()
Then you only call fontSystem.GetFont(size)
which of the 3 do you get?

**Comment by rds1983** [comment]
All of them.
Multiple ttfs are used when you render a glyph for the first time. As it looks over all ttfs unless it finds one containing the requested glyph.
See this code for more details: https://github.com/rds1983/FontStashSharp/blob/7ec7dbff73eb0826fb1a830fcb2c5bb671095c08/src/FontStashSharp/FontSystem.cs#L190

**Comment by zissakos** [comment]
so if I want to use different fonts in my game (like Arial, Tahoma, Times etc.) I need multiple FontSystems, right? My notion that you just need one global FontSystems and then switch between fonts is wrong, correct?

**Comment by rds1983** [comment]
yes and yes.
