### ISSUE TITLE
Issue on Wingding

### ISSUE THREAD

**Issue by dr-prodigy** [rds1983/FontStashSharp#8]
Hi,
thank you for this great piece of code.

Trying to use Wingding as TTF to be rendered, I receive this exception:

stbtt_InitFont failed
System.Exception: stbtt_InitFont failed
   at FontStashSharp.StbTrueTypeSharpFontSource.FromMemory(Byte[] data)
   at FontStashSharp.FontSystem.AddFont(Byte[] data)

Any ideas?

Thx in advance, keep up the good work! 👍

**Comment by rds1983** [comment]
Hello,
Yhanks for the kind words.
Can you share the problematic ttf?

**Comment by dr-prodigy** [comment]
Hey, thank you for your super-fast answer!
Usually it can be found it in any Windows version: it's in fact a pretty standard font (collection of icons / images).
Please let me know if you can't find it: I'll provide you with mine.

Thanks again

**Comment by rds1983** [comment]
Seems to be stb_truetype issue.
I've created the corresponding case: https://github.com/nothings/stb/issues/1086

**Comment by rds1983** [comment]
Well, it seems that wingding.ttf lacks table that maps unicode codepoints to glyph indices(see stb's issue in the previous comment for more details).
Hence it's not supported by FontStashSharp.
