### ISSUE TITLE
Missing Draw overload

### ISSUE THREAD

**Issue by dr-prodigy** [rds1983/FontStashSharp#9]
Hi,
for a MonoGame project, I need to replace this former SpriteBatch.Draw call:

spriteBatch.DrawString(_spriteFont, _text, _rotatedPosition, _color, _rotationAngle, _origin, _scale, _effects, _layerDepth);

with one based on FontStashSharp. More specifically, I need to display rotated text, but FontStashSharp, within its overloads of DrawText(), doesn't seems to support it.

Any suggestion?

Thank you very much in advance

**Comment by rds1983** [comment]
Remove _effects parameter as it's not yet supported.

**Comment by dr-prodigy** [comment]
In fact, I don't really need it.. I put it in my message just to provide the complete method signature, but in my case it's just set to SpriteEffects.None.

What about text rotation (main pain point), instead?

**Comment by rds1983** [comment]
_rotationAngle is supported.
There's even a corresponding sample: https://github.com/rds1983/FontStashSharp/tree/main/samples/FontStashSharp.Samples.RotatingText

**Comment by dr-prodigy** [comment]
Hey, this is great!
No time for more tests now, I'll let you know as soon as I can try your suggestion.
In the meantime, thx again!

**Comment by rds1983** [comment]
yw

**Comment by dr-prodigy** [comment]
Hey there @rds1983 thank you, I confirm that v.0.9.2 was able to sort this out for me.. thank you very much!
